name: napari
channels:
  - conda-forge
dependencies:
  - pip
  - websockify
  - jupyter-server-proxy
  - appdirs
  - cachey
  - imageio
  - importlib-metadata
  - jsonschema
  - ipykernel
  - magicgui
  - napari-console
  - napari-svg
  - numpydoc
  - numpy
  - Pillow
  - pooch
  - psutil
  - PyOpenGL
  - PyYAML
  - pydantic
  - qtpy
  - qtconsole
  - scipy
  - skimage
  - tifffile
  - typing_extensions
  - toolz
  - vispy
  - pyside2
  - wrapt
  - pip:
    # The conda pyside2 package doesn't appear in pip list so napari tries to reinstall it
    # https://github.com/conda-forge/pyside-feedstock/issues/35
    # napari==
    # Manually install in postBuild instead with --no-dependencies
    - napari_plugin_engine
