name: napari
channels:
  - conda-forge
  - ome
dependencies:
  - zeroc-ice36-python
  - omero-py
  - pip
  - websockify
  # https://github.com/napari/napari/blob/v0.2.10/requirements/default.txt
  - dask
  - fsspec
  - imageio
  - ipykernel
  - numpy
  - qtpy
  - qtconsole
  - scipy
  - scikit-image
  - vispy
  - ipython
  - backcall
  - pyopengl
  - pyside2
  - wrapt
  - numpydoc
  - jupyter-server-proxy
  - pip:
    # The conda pyside2 package doesn't appear in pip list so napari tries to reinstall it
    # https://github.com/conda-forge/pyside-feedstock/issues/35
    # napari==
    # Manually install in postBuild instead with --no-dependencies
    - cachey
    - napari_plugin_engine
    - ome-zarr
